apiVersion: monarch.pytorch.org/v1alpha1
kind: MonarchMesh
metadata:
  name: mesh1
  namespace: monarch-tests
spec:
  replicas: 2
  port: 26600
  podTemplate:
    containers:
    - name: worker
      # We use a public image and inline the python commands below.
      image: ghcr.io/meta-pytorch/monarch:2025-12-16-alpha

      # Ensure we always try to pull (helpful during development)
      imagePullPolicy: Always

      # Inline worker script - the public image doesn't have a worker_server.py
      # script.
      # TODO: Move this code to a worker_server.py script in the public image and use
      # that instead.
      command:
        - python
        - -u
        - -c
        - |
          import os
          import socket
          import logging
          from monarch.actor import run_worker_loop_forever
          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger("monarch-worker")
          port = os.environ.get("MONARCH_PORT", "26600")
          hostname = socket.gethostname()
          address = f"tcp://{hostname}:{port}"
          logger.info(f"--- Starting Monarch Worker ---")
          logger.info(f"Identity: {hostname}")
          logger.info(f"Listening on: {address}")
          run_worker_loop_forever(address=address, ca="trust_all_connections")

      env:
      # TODO: Remove after thedavekwon merges his PR.
      # On containers where parent pid=1, the proc_mesh exits quickly without this envvar.
      - name: HYPERACTOR_MESH_BOOTSTRAP_ENABLE_PDEATHSIG
        value: "false"
---
apiVersion: monarch.pytorch.org/v1alpha1
kind: MonarchMesh
metadata:
  name: mesh2
  namespace: monarch-tests
spec:
  replicas: 2
  port: 26600
  podTemplate:
    containers:
    - name: worker
      # We use a public image and inline the python commands below.
      image: ghcr.io/meta-pytorch/monarch:2025-12-16-alpha

      # Ensure we always try to pull (helpful during development)
      imagePullPolicy: Always

      # Inline worker script - the public image doesn't have a worker_server.py
      # script.
      # TODO: Move this code to a worker_server.py script in the public image and use
      # that instead.
      command:
        - python
        - -u
        - -c
        - |
          import os
          import socket
          import logging
          from monarch.actor import run_worker_loop_forever
          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger("monarch-worker")
          port = os.environ.get("MONARCH_PORT", "26600")
          hostname = socket.gethostname()
          address = f"tcp://{hostname}:{port}"
          logger.info(f"--- Starting Monarch Worker ---")
          logger.info(f"Identity: {hostname}")
          logger.info(f"Listening on: {address}")
          run_worker_loop_forever(address=address, ca="trust_all_connections")

      env:
      # TODO: Remove after thedavekwon merges his PR.
      # On containers where parent pid=1, the proc_mesh exits quickly without this envvar.
      - name: HYPERACTOR_MESH_BOOTSTRAP_ENABLE_PDEATHSIG
        value: "false"
